In [ ]:
import os
import pandas as pd
from os.path import join

In [ ]:
src = os.path.join("misinfo-panel-austria", "data", "urls")
os.makedirs(src, exist_ok=True)

In [ ]:
urls = pd.read_csv(join(src, "shortened_urls_r2.csv.gz"),
                     compression="gzip")
len(urls), urls.url.nunique(), urls.domain.nunique()

In [4]:
urls.domain.value_counts().head(15)

domain
bit.ly         1920253
youtu.be       1180666
fb.me          1114080
dlvr.it        1077367
ift.tt          787880
buff.ly         346950
ow.ly           325494
t.co            303569
4sq.com         296828
tmblr.co        266515
goo.gl          223441
instagr.am      150417
tinyurl.com      99375
wp.me            95690
nyti.ms          42557
Name: count, dtype: int64

In [ ]:
last_batch = pd.read_csv(join(src, "unraveled_urls/", "unraveled_urls_23814.csv.gzip"), compression="gzip")

last_batch.status_code.value_counts()

status_code
200.0    67
404.0    15
403.0     7
410.0     2
429.0     1
Name: count, dtype: int64

In [9]:
last_batch.tail(10)

,url,unraveled_url,status_code
90,http://fb.me/1YU8VVriq,Cannot connect to host sploid.gizmodo.com:80 s...,NaN
91,http://goo.gl/87H7cF,https://www.arabiaweather.com/ar/content/%D8%B...,200.0
92,http://ow.ly/XgKU8,https://blog.hootsuite.com/de/wie-sie-fuer-ihr...,404.0
93,http://4sq.com/Oh9qEI,https://www.swarmapp.com/user/9982294/checkin/...,200.0
94,http://ow.ly/qtl1i,https://www.dezeen.com/2013/09/06/disco-volant...,403.0
95,http://wp.me/p3ouIP-1hc,https://abisoghomyan.wordpress.com/2013/07/03/...,200.0
96,http://fb.me/9de7ZjCzb,https://www.spox.com/,200.0
97,https://youtu.be/3cTHXbOVnQQ,https://www.youtube.com/watch?v=3cTHXbOVnQQ&fe...,200.0
98,https://youtu.be/GShSDyrJ2x0,https://www.youtube.com/watch?v=GShSDyrJ2x0&fe...,200.0
99,http://wapo.st/2oBdF0Y,NaN,NaN

In [6]:
last_url = last_batch.url.iloc[-1]
last_url

'http://wapo.st/2oBdF0Y'

In [7]:
# whats the row number of this last url in urls?
last_row = urls[urls.url == last_url].index[0]
last_row

2381399

In [8]:
# print the last 10 rows from that url
urls.iloc[last_row-10:last_row+1]

                                  url    domain
2381389         http://fb.me/V3ZgEy1X     fb.me
2381390        http://fb.me/1YU8VVriq     fb.me
2381391          http://goo.gl/87H7cF    goo.gl
2381392            http://ow.ly/XgKU8     ow.ly
2381393         http://4sq.com/Oh9qEI   4sq.com
2381394            http://ow.ly/qtl1i     ow.ly
2381395       http://wp.me/p3ouIP-1hc     wp.me
2381396        http://fb.me/9de7ZjCzb     fb.me
2381397  https://youtu.be/3cTHXbOVnQQ  youtu.be
2381398  https://youtu.be/GShSDyrJ2x0  youtu.be
2381399        http://wapo.st/2oBdF0Y   wapo.st

In [13]:
# split urls into new and old depending on this row
new_urls = urls.iloc[last_row+1:]
new_urls.head(10)

                                    url       domain
2381400          http://fb.me/3igcB4udE        fb.me
2381401   http://youtu.be/QypkkSY5MKU?a     youtu.be
2381402      http://tinyurl.com/jhzy2tf  tinyurl.com
2381403   http://youtu.be/HarEGVqhfSI?a     youtu.be
2381404          http://fb.me/6rDTdqZTh        fb.me
2381405            http://sco.lt/8ZKNua       sco.lt
2381406  https://tmblr.co/ZktUTv2ezY7Zq     tmblr.co
2381407      http://bit.ly/Streitberger       bit.ly
2381408           https://ti.me/37cwgw0        ti.me
2381409          http://fb.me/7DvahMSQX        fb.me

In [14]:
len(new_urls)

6556591

In [16]:
new_urls.domain.value_counts().head(15)

domain
bit.ly         1444607
fb.me           838191
dlvr.it         792639
youtu.be        791611
ift.tt          690605
buff.ly         273401
ow.ly           231810
4sq.com         198993
t.co            183770
tmblr.co        172227
goo.gl          165197
instagr.am      106639
tinyurl.com      72747
wp.me            65638
nyti.ms          27930
Name: count, dtype: int64

In [19]:
# remove youtu.be, fb.me and t.co
less_urls = new_urls[~new_urls.domain.isin([
    "youtu.be", "fb.me", "t.co", "instagr.am", "tmblr.co", "chang.it"])]
len(less_urls)

4464153

In [20]:
less_urls.domain.value_counts().head(15)

domain
bit.ly         1444607
dlvr.it         792639
ift.tt          690605
buff.ly         273401
ow.ly           231810
4sq.com         198993
goo.gl          165197
tinyurl.com      72747
wp.me            65638
nyti.ms          27930
j.mp             25859
trib.al          25483
yfrog.com        25437
reut.rs          23909
spon.de          21856
Name: count, dtype: int64

In [ ]:
# save the new urls
less_urls.to_csv(join(src, 
"shortened_urls_reduc.csv.gzip"), 
                   compression="gzip", index=False)